## Pytorch Tensor
- Pytorch는 Numpy와 매우 유사하게 텐서 조작 가능

In [1]:
import torch

torch.__version__

'1.7.0+cu101'

In [2]:
t = torch.FloatTensor([0, 1, 2 ,3, 4, 5, 6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [3]:
print(t.dim())  # rank
print(t.size()) # shape
print(t.shape)  # shape
print(t[0], t[1], t[-1]) # Element
print(t[2:5], t[4:-1]) # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])


## Broadcasting
- 엄격하게는 불가능한 연산을, 자동 Broadcasting으로 가능하게 만듦
- 자동으로 이루어지므로 실수로 연산한 경우에도 에러를 유발하지 않기 때문에, 유의해야 함 (디버깅 등에 문제 발생 가능성)

In [4]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2, '\n')

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3]])
print(m1 + m2, '\n')

# 2x1 Vector + 1x2 Tensor
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.]]) 

tensor([[4., 5.]]) 

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication

In [5]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])  # 2 x 2
m2 = torch.FloatTensor([[1], [2]])  # 2 x 1
print('>>> Original Shape :', m1.shape, m2.shape)
print('>>> Original Tensor :')
print(m1)
print(m2)

print('\n>>> Tensor After Multiplication :')
print(m1 * m2)
print(m1.mul(m2))

print('\n>>> Tensor After Matrix Multiplication :')
print(m1.matmul(m2))

>>> Original Shape : torch.Size([2, 2]) torch.Size([2, 1])
>>> Original Tensor :
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])

>>> Tensor After Multiplication :
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])

>>> Tensor After Matrix Multiplication :
tensor([[ 5.],
        [11.]])


## Mean, Sum
- dim=0 는 첫 번째 dimension(row) 기준 dim 유지
- dim=1 는 두 번째 dimension(column) 기준 dim 유지

In [6]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.shape)

print()
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

print()
print(t.mean(dim=0).shape)
print(t.mean(dim=1).shape)
print(t.mean(dim=-1).shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])

tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor([2., 5.])

torch.Size([3])
torch.Size([2])
torch.Size([2])


In [7]:
t = torch.FloatTensor(
    [[[1, 2, 3, 4],
      [4, 5, 6, 7],
      [4, 5, 6, 7]],
     
     [[1, 2, 3, 4],
      [4, 5, 6, 7],
      [4, 5, 6, 7]]]
)

print(t)
print(t.shape)

print()
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

print()
print(t.mean(dim=0).shape)
print(t.mean(dim=1).shape)
print(t.mean(dim=-1).shape)

tensor([[[1., 2., 3., 4.],
         [4., 5., 6., 7.],
         [4., 5., 6., 7.]],

        [[1., 2., 3., 4.],
         [4., 5., 6., 7.],
         [4., 5., 6., 7.]]])
torch.Size([2, 3, 4])

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.],
        [4., 5., 6., 7.]])
tensor([[3., 4., 5., 6.],
        [3., 4., 5., 6.]])
tensor([[2.5000, 5.5000, 5.5000],
        [2.5000, 5.5000, 5.5000]])

torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])


## Max and Argmax
- Max는 Tensor 내에서 가장 큰 값 return
- Argmax는 Tensor 내에서 가장 큰 값의 인덱스 return
- .max() 메서드에 dim 파라미터를 전달하면 값과 인덱스를 둘 다 return

In [8]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.shape, '\n')

print('>>> Max without dim parameter (Total max) :', t.max())

print('\n>>> Max (dim=0) :', t.max(dim=0))
print('>>> Max values (dim=0) :', t.max(dim=0)[0])
print('>>> Max indices - Argmax (dim=0) :', t.max(dim=0)[1])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3]) 

>>> Max without dim parameter (Total max) : tensor(6.)

>>> Max (dim=0) : torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
>>> Max values (dim=0) : tensor([4., 5., 6.])
>>> Max indices - Argmax (dim=0) : tensor([1, 1, 1])


In [9]:
print('>>> Max (dim=1) :', t.max(dim=1))
print('\n>>> Max (dim=-1) :', t.max(dim=-1))

>>> Max (dim=1) : torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))

>>> Max (dim=-1) : torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))
