In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.__version__

'1.7.0+cu101'

In [2]:
# For reproducibility
torch.manual_seed(1)

## Initialize variables

In [3]:
# Data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[3], [5], [7]])
print(x_train.shape)
print(x_train)
print()


# Weights
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
print(W)

torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])

tensor([0.], requires_grad=True)


## Train model

In [4]:
optimizer = optim.SGD([W, b], lr=0.01)

n_epochs = 1000
for epoch in range(n_epochs + 1):
  hypothesis = x_train * W + b
  cost = torch.mean( (hypothesis - y_train)**2 )
  
  optimizer.zero_grad()  # gradient 초기화
  cost.backward()        # gradient 계산
  optimizer.step()       # param 업데이트

  if epoch % 100 == 0:
    print(f'epoch : {epoch:5}  |  cost : {cost.item():10.6f}  |  W : {W.item():.3f}  |  b : {b.item():.3f}')

epoch :     0  |  cost :  27.666666  |  W : 0.227  |  b : 0.100
epoch :   100  |  cost :   0.000899  |  W : 2.035  |  b : 0.921
epoch :   200  |  cost :   0.000556  |  W : 2.027  |  b : 0.938
epoch :   300  |  cost :   0.000343  |  W : 2.021  |  b : 0.951
epoch :   400  |  cost :   0.000212  |  W : 2.017  |  b : 0.962
epoch :   500  |  cost :   0.000131  |  W : 2.013  |  b : 0.970
epoch :   600  |  cost :   0.000081  |  W : 2.010  |  b : 0.976
epoch :   700  |  cost :   0.000050  |  W : 2.008  |  b : 0.981
epoch :   800  |  cost :   0.000031  |  W : 2.006  |  b : 0.985
epoch :   900  |  cost :   0.000019  |  W : 2.005  |  b : 0.988
epoch :  1000  |  cost :   0.000012  |  W : 2.004  |  b : 0.991


## High-level Implementation with `nn.Module`
- 기본적으로 PyTorch의 모든 모델은 제공되는 nn.Module을 inherit 해서 생성

In [5]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)
  
  def forward(self, x):  # 모델이 어떻게 입력값에서 출력값을 계산하는지 알려줍니다
    return self.linear(x)

In [6]:
# Generate model instance and predict y
model = LinearRegressionModel()
print(model)
print('>>> params :', [i.item() for i in model.parameters()])
print()

hypothesis = model(x_train)  # model.forward(x_train)
print(hypothesis)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
>>> params : [0.5152631998062134, -0.44137823581695557]

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward>)


In [7]:
# Train model
model = LinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=0.01)

n_epochs = 1000
for epoch in range(n_epochs + 1):
  hypothesis = model(x_train)
  cost = F.mse_loss(hypothesis, y_train)
  
  optimizer.zero_grad()  # gradient 초기화
  cost.backward()        # gradient 계산
  optimizer.step()       # param 업데이트

  if epoch % 100 == 0:
    W, b = [i.item() for i in model.parameters()]
    print(f'epoch : {epoch:5}  |  cost : {cost.item():10.6f}  |  W : {W:7.3f}  |  b : {b:7.3f}')

epoch :     0  |  cost :  27.398893  |  W :   0.032  |  b :   0.568
epoch :   100  |  cost :   0.011746  |  W :   1.874  |  b :   1.285
epoch :   200  |  cost :   0.007258  |  W :   1.901  |  b :   1.224
epoch :   300  |  cost :   0.004485  |  W :   1.922  |  b :   1.176
epoch :   400  |  cost :   0.002772  |  W :   1.939  |  b :   1.139
epoch :   500  |  cost :   0.001713  |  W :   1.952  |  b :   1.109
epoch :   600  |  cost :   0.001058  |  W :   1.962  |  b :   1.086
epoch :   700  |  cost :   0.000654  |  W :   1.970  |  b :   1.067
epoch :   800  |  cost :   0.000404  |  W :   1.977  |  b :   1.053
epoch :   900  |  cost :   0.000250  |  W :   1.982  |  b :   1.042
epoch :  1000  |  cost :   0.000154  |  W :   1.986  |  b :   1.033
