In [1]:
import torch
from collections import OrderedDict

# check device
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# set seed for reproducibility
torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

torch.__version__

'1.7.0+cu101'

## Perceptron and XOR problem
- Perceptron : Hidden Layer를 갖지 않고 오직 Input & Output Layer 로만 구성된 인공신경망
- Perceptron 모델로는 XOR (두 요소가 다를 때 1, 같을 때 0) 문제를 풀 수 없음

In [2]:
# prepare data for xor problem
x_train = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
y_train = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

x_train

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [3]:
# train model
model = torch.nn.Sequential(OrderedDict([
    ('linear', torch.nn.Linear(2, 1, bias=True)),
    ('softmax', torch.nn.Sigmoid()),
]))

optimizer = torch.optim.SGD(model.parameters(), lr=1e-1)
criterion = torch.nn.BCELoss().to(device)

n_epochs = 10000
for epoch in range(n_epochs+1):
  hypothesis = model(x_train)
  cost = criterion(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%1000 == 0:
    print(f'epoch : {epoch:6}  |  cost : {cost:10.6f}')

epoch :      0  |  cost :   0.727397
epoch :   1000  |  cost :   0.693148
epoch :   2000  |  cost :   0.693147
epoch :   3000  |  cost :   0.693147
epoch :   4000  |  cost :   0.693147
epoch :   5000  |  cost :   0.693147
epoch :   6000  |  cost :   0.693147
epoch :   7000  |  cost :   0.693147
epoch :   8000  |  cost :   0.693147
epoch :   9000  |  cost :   0.693147
epoch :  10000  |  cost :   0.693147


In [4]:
# compute accuracy
with torch.no_grad():
  hypothesis = model(x_train)
  predicted = (hypothesis > 0.5).float()
  accuracy = (predicted == y_train).float().mean()
  print(f'>>> hypothesis :\n {hypothesis} \n\n>>> label :\n {y_train} \n\n>>> accuracy : {accuracy}')

>>> hypothesis :
 tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000]]) 

>>> label :
 tensor([[0.],
        [1.],
        [1.],
        [0.]]) 

>>> accuracy : 0.5
