## View
- numpy .reshape() 메서드와 동일한 기능

In [1]:
import torch

torch.__version__

'1.7.0+cu101'

In [2]:
ft = torch.FloatTensor(
    [[[1, 2, 3, 4],
      [4, 5, 6, 7]],
     
     [[1, 2, 3, 4],
      [4, 5, 6, 7]]]
)
print(ft.shape)
print(ft)

torch.Size([2, 2, 4])
tensor([[[1., 2., 3., 4.],
         [4., 5., 6., 7.]],

        [[1., 2., 3., 4.],
         [4., 5., 6., 7.]]])


In [3]:
ft_view = ft.view(-1, 4)
print(ft_view.shape)
print(ft_view)

torch.Size([4, 4])
tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.],
        [1., 2., 3., 4.],
        [4., 5., 6., 7.]])


In [4]:
ft_view = ft.view(-1, 1, 4)
print(ft_view.shape)
print(ft_view)

torch.Size([4, 1, 4])
tensor([[[1., 2., 3., 4.]],

        [[4., 5., 6., 7.]],

        [[1., 2., 3., 4.]],

        [[4., 5., 6., 7.]]])


## Squeeze
- numpy .ravel() 메서드와 동일한 기능

In [5]:
ft = torch.FloatTensor(
    [[0], [1], [2]]
)
print(ft.shape)
print(ft)

torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])


In [6]:
ft_sqz = ft.squeeze()
print(ft_sqz.shape)
print(ft_sqz)

torch.Size([3])
tensor([0., 1., 2.])


In [7]:
ft_sqz = ft.squeeze(dim=0)
print(ft_sqz.shape)
print(ft_sqz)

ft_sqz = ft.squeeze(dim=1)

print(ft_sqz.shape)
print(ft_sqz)

torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3])
tensor([0., 1., 2.])


## Type Casting
- 텐서의 타입 변환

In [8]:
lt = torch.LongTensor([1,2,3,4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [9]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)  # dtype uint8
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [10]:
bt = lt==3
print(bt)  # dtype bool
print(bt.long())
print(bt.float())

tensor([False, False,  True, False])
tensor([0, 0, 1, 0])
tensor([0., 0., 1., 0.])


## Concatenate

In [11]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(x)
print()

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))
print(torch.cat([x, y], dim=-1))

tensor([[1., 2.],
        [3., 4.]])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [12]:
x = torch.FloatTensor([1, 2])
y = torch.FloatTensor([3, 4])
z = torch.FloatTensor([5, 6])

print(x)
print()

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([1., 2.])

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [13]:
print(torch.cat([x, y, z]).view(-1, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


## Ones_like and Zeros_like
- Dimension 뿐만 아니라 device(CPU, GPU, Multiple device)도 유지해 에러를 방지

In [14]:
x = torch.FloatTensor([[1, 2, 3], [3, 4, 5]])

print(x)
print()

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 2., 3.],
        [3., 4., 5.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
